# Generated by Django 5.0.4 on 2024-05-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SD", "Разработчик ПО (Software Developer)"),
                            (
                                "STE",
                                "Инженер по тестированию программного обеспечения (Software Test Engineer)",
                            ),
                            (
                                "SA",
                                "Архитектор программного обеспечения (Software Architect)",
                            ),
                            ("TW", "Технический писатель (Technical Writer)"),
                            ("PM", "Продуктовый менеджер (Product Manager)"),
                            ("PJM", "Менеджер проекта (Project Manager)"),
                            ("BA", "Аналитик бизнес-требований (Business Analyst)"),
                            ("UXUI", "UX/UI дизайнер (UX/UI Designer)"),
                            ("DEVOPS", "DevOps инженер (DevOps Engineer)"),
                            (
                                "SYSADM",
                                "Системный администратор (System Administrator)",
                            ),
                            (
                                "SSE",
                                "Инженер сопровождения ПО (Software Support Engineer)",
                            ),
                            ("DA", "Аналитик данных (Data Analyst)"),
                            (
                                "INFOSEC",
                                "Инженер информационной безопасности (Information Security Engineer)",
                            ),
                            (
                                "TAE",
                                "Специалист по автоматизации тестирования (Test Automation Engineer)",
                            ),
                            ("DE", "Инженер по развертыванию (Deployment Engineer)"),
                        ],
                        max_length=7,
                    ),
                ),
                ("date_of_employment", models.DateField(auto_now_add=True)),
                ("salary_in_dollars", models.IntegerField(default=0)),
                (
                    "supervisor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
