# Generated by Django 5.0.4 on 2024-05-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SD", "Software Developer"),
                            ("STE", "Software Test Engineer"),
                            ("SA", "Software Architect"),
                            ("TW", "Technical Writer"),
                            ("PM", "Product Manager"),
                            ("PJM", "Project Manager"),
                            ("BA", "Business Analyst"),
                            ("UXUI", "UX/UI Designer"),
                            ("DEVOPS", "DevOps Engineer"),
                            ("SYSADM", "System Administrator"),
                            ("SSE", "Software Support Engineer"),
                            ("DA", "Data Analyst"),
                            ("INFOSEC", "Information Security Engineer"),
                            ("TAE", "Test Automation Engineer"),
                            ("DE", "Deployment Engineer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_of_employment", models.DateField(auto_now_add=True)),
                ("salary_in_dollars", models.IntegerField(default=0)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subordinates",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
